version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest-full
    networks:
      - default
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
      # resources:
      #   limits:
      #     memory: 128M
      #   reservations:
      #     memory: 64M

  action_server:
    image: rasa/rasa-sdk:latest
    networks:
      - default
    volumes:
      - ./actions:/app/actions
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s

  rasa-x:
    restart: always
    image: "rasa/rasa-x:latest"
    networks:
      - default
    expose:
      - "5002"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./domain.yml:/app/domain.yml
      - ./config.yml:/app/config.yml
      - ./environments.yml:/app/environments.yml
      - ./logs:/logs
      - ./auth:/app/auth
    environment:
      SELF_PORT: "5002"
      DB_DATABASE: "rasa"
      RASA_MODEL_DIR: "/app/models"
      RABBITMQ_QUEUE: "rasa_production_events"
      PASSWORD_SALT: "rasa"
      RASA_X_USER_ANALYTICS: "0"
      SANIC_RESPONSE_TIMEOUT: "3600"
    depends_on:
      - db

  db:
    restart: always
    image: "bitnami/postgresql:11.2.0"
    networks:
      - default
    expose:
      - "5432"
    environment:
      POSTGRESQL_USERNAME: "rasa"
      POSTGRESQL_PASSWORD: "rasa"
      POSTGRESQL_DATABASE: "rasa"
    volumes:
      - ./postgresql_data:/bitnami/postgresql

  rabbit:
    restart: always
    image: "bitnami/rabbitmq:3.7.15"
    networks:
      - default
    environment:
      RABBITMQ_HOST: "rabbit"
      RABBITMQ_USERNAME: "rasa"
      RABBITMQ_PASSWORD: "rasa"
      RABBITMQ_DISK_FREE_LIMIT: "{mem_relative, 0.1}"
    expose:
      - "5672"

networks:
  default:
    external: false